# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 192eb653e74f8279e0920086aac3bcbcba2ccd078d5858faaff75b059a20d2adf01f19a468c24ddd383739e90946063a2a1b6be6b3ba0f4dbb68f3958ff90744

test:
  secret_key_base: 4737ba7791868775fa6adb41351849f277fb6dca3253cae115dfbea7b6d651fba0f7644252c3f5f2f3a9e45832f1bfacaed660fbb3eb520b35401c3f9cbc76fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
